//fugu_unable_to_connect_internet: "Não é possível conectar-se à Internet"
//fugu_no_internet_connection_retry: "Sem ligação à Internet \ nToque para repetir"
//hippo_something_wrong: "Algo deu errado \ nToque para repetir"
//fugu_new_conversation: "New Conversation"
//fugu_loading: "Carregando..."
//fugu_powered_by: "Corre em"
//fugu_text: "Hipopótamo"
//fugu_no_gallery: "Galeria não encontrado neste telefone."
//fugu_camera: "Câmera"
//fugu_gallery: "Galeria"
//fugu_document: "documentos"
//fugu_payment: "Forma de pagamento"
//fugu_audio: "auditivo"
//fugu_pdf: "Documento"
//fugu_retry: "Repetir"
//fugu_attachment: "anexo de imagem"
//fugu_send_message: "Envie uma mensagem..."
//fugu_cancel: "Cancelar"
//fugu_ok: "Está bem"
//fugu_file_not_found: "Desculpe este arquivo não está disponível no seu dispositivo é"
//fugu_support: "Apoio, suporte"
//hippo_could_not_send_message: "Não foi possível enviar a sua mensagem"
//hippo_tap_to_retry: "Toque para repetir"
//hippo_no_internet_cancel: "Cancelar"
//fugu_not_connected_to_internet: "Não conectado a Internet"
//fugu_connecting: "Conectando ..."
//fugu_connected: "Conectado"
//fugu_no_conversation_found: "Não foram encontradas conversas"
//fugu_no_conversation: "Nós não conseguimos encontrar \ nconversations neste caixa de entrada"
//fugu_tap_to_view: "<I> Toque para ver </ i>"
//fugu_agent_actions: "AÇÕES"
//fugu_show_more: "MOSTRE MAIS..."
//fugu_leave_comment: "Deixe um comentário"
//fugu_no_data_found: "Nenhum dado encontrado"
//hippo_message_sucessfully: "Seu pedido foi enviado com sucesso"
//hippo_text: "Hipopótamo"
//hippo_smile_rating_terrible: "Terrível"
//hippo_smile_rating_bad: "Mau"
//hippo_smile_rating_okay: "OK"
//hippo_smile_rating_good: "Boa"
//hippo_smile_rating_great: "Ótimo"
//hippo_search: "Search & # 8230"
//hippo_error_no_countries_found: "Nenhum país Encontrado!"
//hippo_country_picker_header: "Selecione o pais"
//call_again: "Ligue novamente"
//hippo_select_string: "selecionar"
//hippo_rationale_ask: "Este aplicativo pode não funcionar corretamente sem as permissões solicitadas."
//hippo_rationale_ask_again: "Este aplicativo pode não funcionar corretamente sem as permissões solicitadas. Abra o aplicativo tela de configurações para modificar permissões de aplicativos."
//title_settings_dialog: "permissões necessárias"
//vw_confirm: "Feito"
//vw_rationale_storage: "Precisa de Permissão de armazenamento de leitura para a colheita Arquivos"
//vw_up_to_max: "Já até máx"
//vw_no_photo_app: "Nenhuma foto App neste telefone!"
//vw_all: "Todos"
//hippo_browse_other_doc: "Consulte outros docs & # 8230;"
//hippo_large_file: "tamanho do arquivo não pode ser maior que"
//hippo_attachment_file: "Ficheiro em anexo"
//no_handler: "Este tipo de arquivo não é suportado"
//uploading: "Enviando"
//uploading_in_progress: "upload em andamento"
//unknown_message: "Esta mensagem não suporta em seu aplicativo atual"
//hippo_broadcast_detail: "transmissão Detalhes"
//hippo_recipients: "destinatários"
//hippo_add_an_option: "Adicionar uma opção"
//hippo_request_payment: "pagamento pedido"
//hippo_item_price: "Digite Preço"
//hippo_item_description: "Digite Descrição"
//hippo_currency: "Moeda"
//fugu_title: "Título"
//hippo_enter_title: "Digite Título"
//hippo_title_item_price: "Preço"
//hippo_title_item_description: "Descrição"
//hippo_total_count: "Preço total"
//hippo_empty_transaction_id: "TransactionID não pode ser esvaziar"
//hippo_empty_other_user_unique_keys: "Outro usuário variedade chaves únicas não pode estar vazio"
//talk_to: "Criar Conversation"
//hippo_history: "conversações"
//logout: "Sair"
//hippo_something_wentwrong: "Algo deu errado \ nTente novamente mais tarde"
//app_guarantee: "Garantia"
//hippo_activity_image_trans: "activity_image_transition"
//hippo_read_more: "consulte Mais informação"
//hippo_read_less: "Leia Menos"
//error_msg_yellow_bar: "conexão de Internet lenta."
//hippo_storage_permission: "Por favor permissão de armazenamento de concessão"
//hippo_netbanking: "net Banking"
//hippo_pay_with_netbanking: "net Banking"
//hippo_payfort: "Payfort"
//hippo_paytm: "Paytm"
//hippo_card: "Cartão"
//hippo_pay_with_paymob: "Paymob"
//hippo_pay_with_razorpay: "Card / Net Banking"
//float_label_start_chat: "Novo suporte via Chat"
//hippo_pay_with_paytm: "Pague com Paytm"
//hippo_stripe: "Listra"
//hippo_fetching_payment_methods: "métodos de pagamento Buscando ..."
//hippo_no_payment_methods: "Nenhum método de pagamento disponíveis"
//hippo_you_have_no_chats: "Você não tem chats"
//hippo_clear_all_notification: "Limpar tudo"
//hippo_find_an_expert: "Encontre um perito"
//hippo_no_chat_init: "Parece que você ainda não começou a sua jornada de amigos ainda, lançar-lo agora!"
//hippo_rating_review: "Avaliação e"
//hippo_cancel_payment: "Anular Pagamento"
//cancel_payment_text: "Tem certeza de que deseja cancelar o pagamento?"
//hippo_no: "Não"
//hippo_yes_cancel: "Sim, o Anular"
//hippo_payment_title: "Forma de pagamento"
//hippo_payment_loader: "Por favor, aguarde \ n Redirecionando para o link de pagamento"
//fugu_menu_retry: "Repetir"
//vw_no_video_app: "No aplicativo de vídeo encontrados"
//hippo_chat_support: "Suporte bate-papo"
//hippo_submit: "Enviar"
//hippo_call: "Ligar"
//hippo_chat: "Bate-papo"
//hippo_notifications_title: "notificações"
//hippo_no_notifications: "Nenhuma notificação"
//hippo_notifications_deleted: "notificação eliminado"
//hippo_chats: "Bate-papo"
//hippo_notifications: "notificações"
//hippo_current: "Atual"
//hippo_past: "Passado"
//hippo_yes: "sim"
//hippo_logout_msg: "Tem certeza que deseja sair?"
//fugu_create_conversation: "Criar conversa"
//hippo_no_internet_connected: "Sem Internet Conectado"
//hippo_you: "Vocês"
//hippo_sent_a_msg: "enviou uma mensagem"
//fugu_voice: "voz"
//fugu_video: "vídeo"
//hippo_call_with_you: "chamar com você"
//hippo_customer_missed_a: "Cliente perdeu uma"
//hippo_you_missed_a: "Você perdeu uma"
//hippo_call_with: "ligue com"
//hippo_call_ended: "Chamada finalizada"
//hippo_the: "o"
//hippo_something_went_wrong: "Algo deu errado. Por favor, tente novamente"
//hippo_file_already_in_queue: "Já arquivos na fila. Por favor, espere"
//hippo_grant_permission: "conceder permissão por favor"
//hippo_pay_btnText: "Pagamento"
//hippo_error_msg_sending: "Erro na mensagem de publicação"
//hippo_feature_no_supported: "Este recurso não é suportado"
//hippo_nochats: "Você não tem chats."
//hippo_writereview: "Escreva uma crítica"
//hippo_minimum_Multiselection: "Por favor, selecione pelo menos uma opção"
//hippo_enter_number_only: "Introduzir valores numéricos apenas"
//hippo_enter_valid_email: "Digite e-mail válido"
//hippo_field_cant_empty: "O campo não pode estar vazio"
//hippo_fill_pre_field: "Por favor, preencha os campos anteriores"
//hippo_enter_valid_price: "Por favor, indique preço válido para o item"
//hippo_invalid_price: "preço inválido"
//hippo_alert: "Alerta!"
//hippo_file_not_supported: "tipo de arquivo não suportado! Você deseja abrir com outros aplicativos?"
//hippo_with_country_code: "com código de país"
//hippo_enter_phone_number: "Digite seu telefone"
//hippo_enter_valid_phn_no: "Digite o número de telefone válido"
//hippo_save_plan: "Guardar Plano"
//hippo_update_plan: "Plano de atualização"
//hippo_no_chat: "Parece que você ainda não começou qualquer bate-papo ainda, lançar-lo agora!"
//hippo_call_back: "Ligue de volta"
//hippo_missed: "Perdido"
//hippo_paid: "- PAGO -"
//hippo_ongoing: "Em andamento"
//hippo_at: "em"
//hippo_pending: "- PENDENTE -"
//hippo_free: "Livre"
//hippo_photo_video_library: "Foto & Video Biblioteca"
//hippo_video: "Vídeo"
//hippo_files: "arquivos"
//hippo_emptymessage: "Por favor, indique algum texto"
//hippo_missed_call: "Chamada Perdida"
//hippo_the_voice_call: "A chamada de voz"
//hippo_the_video_call: "A chamada de vídeo"
//hippo_the_voice_call_ended: "A chamada de voz terminou"
//hippo_the_video_call_ended: "A chamada de vídeo terminou"
//hippo_all_agents_busy: "Todos os agentes estão ocupados no momento, nós wll se conectar com você em breve"
//hippo_copy_to_clipboard: "Copiado para a área de transferência"
//hippo_proceed_to_pay: "Proceder ao pagamento"
//hippo_today: "Hoje"
//hippo_yesterday: "Ontem"
//hippo_no_notifications: "Nenhuma notificação encontrado"
//hippo_call_calling: "CHAMANDO ..."
//hippo_call_ringing: "TOQUE..."
//hippo_disconnect: "DESLIGAR ..."
//hippo_busy_on_call: "Ocupado com outra chamada ..."
//hippo_call_declined: "chamada Recusado"
//hippo_audio_call: "de áudio de chamada"
//hippo_call_rejected: "Ligação rejeitada"
//hippo_calling_from_old: "não tem o aplicativo atualizado, Chamar pelo SDK velho ..."
//hippo_call_hungup: "DESLIGAR"
//hippo_call_outgoing: "Chamada em curso"
//hippo_call_incoming: "Chamada recebida"
//hippo_call_incoming_video_call: "Incoming Chamada de vídeo"
//hippo_call_incoming_audio_call: "Entrada de áudio de chamada"
//hippo_payment_request: "Pedido de Pagamento"
//hippo_call_versionmismatch: "Incompatibilidade de versão"
//hippo_callanyway: "Chamada de qualquer maneira"
//hippo_select_a_plan: "selecionar um plano"
//hippo_audio_picker: "áudio Picker"
//hippo_image_picker: "imagem Picker"
//hippo_doc_picker: "documentos"
//hippo_video_picker: "vídeo Picker"
//hippo_secure_payment: "100% de pagamento seguro"
//hippo_is_typing: "está digitando..."
//hippo_clear: "Claro"
//RATING_AND_REVIEW: "Avaliação e"
//PAYMENT_REQUESTED: "Um pagamento é solicitado a você"
//Hippo_Select_Plan: "Selecione um Plano"
//hippo_conversation_closed: "Conversação tiver sido fechada"
//hippo_calling_you: "está chamando você ......"
//hippo_send_photo: "enviar foto"
//NEW_CUSTOMER: "Novo cliente"
//hippo_back: "Costas"
//hippo_thanks_feedback: "Obrigado pelo seu feedback!"
//hippo_message_not_allow : "Você não tem permissão para compartilhar dados pessoais."
//hippo_settings : "CONFIGURAÇÕES"
//hippo_not_now  : "AGORA NÃO"
//hippo_answer : "Responda"
//hippo_reject : "Rejeitar"
//hippo_swipe_accept : "Deslize para cima para aceitar"
//hippo_swipe_reject : "Deslize para cima para rejeitar"
//hippo_calling_connection : "Ligando-o a sua reunião"
//hippo_Thankyou_Feedback : "Obrigado por seus comentários!"
//hippo_video_call : "Video chamada"
//hippo_message_deleted : "eliminou esta mensagem."
//hippo_edited : "editado"
//hippo_copy_text : "cópia de"
//hippo_delete_text : "Excluir"
//hippo_edit_text : "Editar"
//hippo_delete_this_message : "Você tem certeza que quer deletar esta mensagem?"
//hippo_delete_for_everyone : "Excluir para todos"